### ISSUE TITLE
Make it possible to access Tasker variables from scripts

### ISSUE THREAD

**Issue by fornwall** [termux/termux-tasker#1]
From https://www.reddit.com/r/tasker/comments/5mq7rc/psa_you_can_install_and_automate_things_like_curl/:

> OK, so I'll just go with my own use-case as an example. I'm using Tasker to automatically write metadata to pictures as soon as I've taken them and exited the camera app. I do this by calling a Termux script from my Tasker task that runs perl exiftool [commands] /path/to/file.
In order for this to work, I obviously have to get the image file paths first of all. This is done by having Tasker read the camera folder and checking to see if there are image files that have been created since I last opened the camera app. The paths to these files are then stored in a local Tasker variable—let's say %paths.
Now I would like to pass this variable to the Termux script that I call at the end of my task in order to do something like perl exiftool [commands] $paths. What I have to do instead is write a text file in Tasker with the %paths variable and then have my Termux script read the information in that file to its own variable, which works but is kind of clunky.
I know I could rework my script to get the file paths directly in Termux, but it would be a lot more simple and versatile for a whole bunch of other use cases if it were possible to pass variables directly from Tasker.

**Comment by PacoBell** [comment]
I personally want to feed YouTube URLs into youtube-dl from the YouTube app Share to "Copy link" to clipboard. Tasker already has a monitor for the %CLIP variable. This would be so easy if it were possible.

**Comment by Neo-Oli** [comment]
@PacoBell You can do something very similar to this without tasker. You can create a script at `$HOME/bin/termux-url-opener` containing the command:
`youtube-dl $@`

Then you can go to a youtube video and click the share button. Then you can, from the youtube app, share to "Termux". 

This will automatically launch `$HOME/bin/termux-url-opener http://youtube.com?v=xxxxxxxx`

**Comment by PacoBell** [comment]
Awesome! I suppose I'd have to regex parse the URL in order to trigger different services depending on the domain.

**Comment by Neo-Oli** [comment]
@PacoBell Yes. Or you can do what I do: 
$HOME/bin/termux-url-opener
```
#!/data/data/com.termux/files/usr/bin/bash
cd ~/bin/
com=`ls --color=never url-*|fzf`
~/bin/$com $@
```
I then have various `url-<name>` scripts in `$HOME/bin` like
url-youtube-dl
```
youtube-dl $@
```
When I share I get this screen which lets me choose which script I want to run
![screenshot_20170302-094514](https://cloud.githubusercontent.com/assets/7983745/23499693/69e76016-ff2d-11e6-983c-f9bd1aa7b808.png)

**Comment by janru** [comment]
I'd like to pass a tasker variable to a termux script in the background. I assume, the solution above does not fit my needs, because it opens termux in the foreground, right?
let's say we have the script dosth.sh. Then I'd like to pass the string "myMessage" by executing  '~/.termux/tasker/dosth.sh myMessage' which produces an error.
Could you please disable the check if the file "dosth.sh myMessage" exists? Or add a possibility to append parameters?

**Comment by TheNothingMan** [comment]
> Could you please disable the check if the file "dosth.sh myMessage" exists? Or add a possibility to append parameters?

I really would like to see that, too. Limiting Tasker to start scripts without parameters cuts down Tasker+Termux' possibilities.

**Comment by TheNothingMan** [comment]
While I am trying to be patient, I just have to ask: Will there be a version that contains the argument stuff at Google Play soon?
If there are any problems left with my code, I would be glad to see if I can help.

**Comment by fornwall** [comment]
@TheNothingMan Thanks for your pull request - great work! I've just tagged the release and updated it to Google Play, so it should be available in a few hours as an update.

It should also appear on F-Droid within a day or so.
