### ISSUE TITLE
Tasker variables in the arguments field?

### ISSUE THREAD

**Issue by Sokonomi** [termux/termux-tasker#10]
Is it possible to put Tasker variables into the arguments field?

It would cut out so many steps; To get around it, I first write the variables to a file, then have a script parse the data from said file and then finally run the intended script with the actual arguments I needed.

Just plopping a buncha %VARs into the Termux:Task argument field would make life somuch easier.

**Comment by Sokonomi** [comment]
Append; I just saw there was a fork that got merged that supposedly added the use of tasker variables. How do you do it though? Please work on putting up some documentation about this plugin; Apparently it does stuff that only the devs themselves know about?

**Comment by cherryleafroad** [comment]
I've been putting Tasker variables into the arguments field, seems to work fine for me

**Comment by leo60228** [comment]
@Sokonomi It seems that you can just prefix arguments with `%` and they get treated as Tasker variables. Works with Automate, which I prefer to Tasker.

**Comment by jschwinger23** [comment]
for the variables generated by profile, like `App Changed: Package(%app_package)`, you have to set another variable to the value in task to make tasker:termux can parse properly, like `%var=%app_package`, then just fill the `arguments` with `%var`

**Comment by dekiesel** [comment]
> for the variables generated by profile, like `App Changed: Package(%app_package)`, you have to set another variable to the value in task to make tasker:termux parse properly, like `%var=%app_package`, then just fill the `arguments` with `%var`

Thanks, that was it! It seems you need to turn global variables (variables containing one or more  uppercase characters) into local variables (variables ONLY containing lower case characters). I just tried this with a "Variable Set" and it works as expected.

**Comment by agnostic-apollo** [comment]
Only local variables (all lowercase letters) can be passed to plugins in Tasker and not global. Check [TaskerPlugin Library variableNameValid() function](https://github.com/termux/termux-tasker/blob/3e70898d7921e3634e4a45f259356253ecff1ce0/app/src/main/java/com/termux/tasker/TaskerPlugin.java#L191).
