### ISSUE TITLE
bash: extglob off in the plugin - not possible to enable it

### ISSUE THREAD

**Issue by francwalter** [termux/termux-tasker#102]
**Problem description**

I have a Task with Termux Tasker Plugin where I have a for-do-loop with extended globbing (excluding a file mask). Here a simplified example with bash. Executable: /path/to/bash, Stdin: this command:

`for file in !(*.gpg); do echo ${file}; done;`

But (in Termux Tasker Plugin) this is not working, I get the error (stderr):

```
/data/data/com.termux/files/usr/bin/bash: line 1: syntax error near unexpected token `('
/data/data/com.termux/files/usr/bin/bash: line 1: `for file in !(*.gpg); do echo ${file}; done;'
```

In Termux app this is working, here the setting of extglob is on (and working):

```
$ shopt extglob
extglob          on
```

But in Termux Tasker Plugin it is off, I put into Stdin:

`shopt extglob`

and the output (stdout) is:

`extglob        off`

If I disable extglob in Termux app (which is enabled by default there) I have this error:

```
$ shopt -u extglob
$ for file in !(*.gpg); do echo ${file}; done;
bash: !: event not found
```

which shows, that extglob is really the culprit. 
So I tried to enable extglob in Termux Tasker Plugin before my use of it, with e.g. this Stdin command:

`shopt -s extglob; for file in !(*.gpg); do echo ${file}; done;`

But still the same error, setting extglob seems not to change anything:

```
/data/data/com.termux/files/usr/bin/bash: line 1: syntax error near unexpected token `('
/data/data/com.termux/files/usr/bin/bash: line 1: `shopt -s extglob; for file in !(*.gpg); do echo ${file}; done;'
```

I can enable extglob (in the plugin) with this command (in Stdin):

`shopt -s extglob; shopt extglob`

and the stdout is:

`extglob       on`

but it  didnt work if I use that in the loop command, see above.

Is there a way to get extglob working in the Termux Tasker Plugin?
Thanks.frank

**Additional information**

* Termux application version: 0.118.0
* Termux Tasker Plugin version: 0.6.0
* Tasker version: 6.3.6-beta (direct purchased version)
* Android OS version: 9.0
* Device model: Xiaomi Mi A1 (unrooted)

**Comment by agnostic-apollo** [comment]
>extglob changes the way certain characters are parsed. It is necessary to have a newline (not just a semicolon) between shopt -s extglob and any subsequent commands to use it. You cannot enable extended globs inside a group command that uses them, because the entire block is parsed before the shopt is evaluated. Note that the typical function body is a group command. An unpleasant workaround could be to use a subshell command list as the function body.

https://mywiki.wooledge.org/glob#extglob

**Comment by francwalter** [comment]
> extglob changes the way certain characters are parsed. It is necessary to have a newline (not just a semicolon) between shopt -s extglob and any subsequent commands to use it. ...

This was the whole trick? A new line???
That was easy 😄 

Now it is working with Stdin:

```
shopt -s extglob;
for file in !(*.gpg); do echo "${file}"; done;
```
no more error 😄 
Thank you @agnostic-apollo very much! You are the crack coder 😄

**Comment by agnostic-apollo** [comment]
Pretty much. Shell parses scripts per line, so extglob changes take effect from next line.

You are welcome.

**Comment by TomJo2000** [comment]
Newlines and `;` are interchangeable in *almost* all cases.
This is one of the cases where they're not.
The same applies for all shell options that effect parsing.
