### ISSUE TITLE
Error message when adding termux action in Tasker

### ISSUE THREAD

**Issue by Toug19** [termux/termux-tasker#109]
**Problem description**

I installed last version of the apk on my pixel 4a 5G Android 14 device. Tasker is installed.
When I try to add a termux action on tasker, I'm getting a message: 
Error: plugin error: missing, disabled, not exported or not permission receiver, or too many receiver.

**Steps to reproduce**

Install apk of termux-tasker apk, open tasker, create new task, new action, select Termux

**Expected behavior**

Termux invite screen to create tasker termux action

**Additional information**

* Termux-tasker application version: 0.6.0
* Termux application version: 0.119.0-beta.1
* Android OS version: 14
* Device model: Pixel 4a 5G

**Comment by twaik** [comment]
You did not provide any information about the issue. Closing this as invalid.

**Comment by Toug19** [comment]
modified, they were as comment.

**Comment by twaik** [comment]
This issue should be reported to https://github.com/termux-play-store since termux in GP in fork we do not have access to.

**Comment by Toug19** [comment]
I updated the issue description as I just removed the GP version and installed the 0.119.0-beta.1 and I got exact same issue.

**Comment by Toug19** [comment]
https://github.com/user-attachments/assets/6b9b4d48-e752-4e08-90bf-01d0365da458

**Comment by twaik** [comment]
Did you set it up right as described in https://github.com/termux/termux-tasker ?

**Comment by Toug19** [comment]
Sorry and thanks it solved my issue.

**Comment by Toug19** [comment]
was missing a configuration step.
