### ISSUE TITLE
Not able to run scripts from termux tasker plugin

### ISSUE THREAD

**Issue by anupamsingh81** [termux/termux-tasker#11]
I created the /data/data/com.termux/files/home/.termux/tasker folder and placed a shell script in it
I can run scripts same from directory  but not from my termux tasker  plugin

from termux app

$ sh /data/data/com.termux/files/home/.termux/tasker/script1.sh

$ sh ./data/data/com.termux/files/home/.termux/tasker/script1.sh

sh: 0: Can't open ./data/data/com.termux/files/home/.termux/tasker/script1.sh

$ bash /data/data/com.termux/files/home/.termux/tasker/script1.sh

$ bash ./data/data/com.termux/files/home/.termux/tasker/script1.sh

bash: ./data/data/com.termux/files/home/.termux/tasker/script1.sh: No such file or directory

$ cd /data/data/com.termux/files/home/.termux/tasker

$ ls

num.py script.sh script1.sh

$ sh script1.sh

num.py script.sh script1.sh
from termux-tasker plugin

exec("/data/data/com.termux/files/home/.termux/tasker/script1.sh"): No such file or directory

**Comment by Grimler91** [comment]
I'm guessing your script isn't executable. Try adding a shebang as the first line (`#!/data/data/com.termux/files/usr/bin/sh`) and make it executable with `chmod u+x ~/.termux/tasker/script1.sh`.

**Comment by anupamsingh81** [comment]
Thank you..
I had created these files as root user with esfile explorer and hence was running into errors even on changing ownership.

Worked with your advice.

**Comment by anupamsingh81** [comment]
Thank you..
I had created these files as root user with esfile explorer and hence was running into errors even on changing ownership.

Worked with your advice.
