### ISSUE TITLE
Script called from Tasker doesn't work correctly.

### ISSUE THREAD

**Issue by ionlyaskforeden** [termux/termux-tasker#12]
Hello,

first please bare with my low skills I am rather a user than developer.. 

In Tasker I have a task that creates a playlist with few videos from my subs. 

In termux I wrote a small script that downloads that playlist and converts to mp3 with youtube-dl.
(the sh script for reference: https://pastebin.com/Wsqnvx1B , I use the files in the /variables dir as variables from tasker) 

The script works flawlessly launched from within Termux with "./" but from Tasker it won't recognize the URL. When launching the script with terminal window I get this result: 

----------------------------------------------------

ERROR: '' is not a valid URL. Set --default-search "ytsearch" (or run  youtube-dl "ytsearch:" ) to search YouTube

[Process completed (code 1) - press Enter]

-----------------------------------------------------

It looks like the script won't read the file with the link when launched from Tasker.. 

Logcat: https://pastebin.com/guHXqMTx

I noticed "12.47.08#ActionArgBundle: error: Termux: replace specified for null or non-string extra: com.termux.tasker.extra.TERMINAL" in the first line but unfortunately I don't know what that means.

Any help would be much appreciated and I'm willing to provide any info. Thanks in advance. 

Regards,

ionlyaskforeden

**Comment by Grimler91** [comment]
Try adding a proper shebang to the script, i.e. add `#! /data/data/com.termux/files/usr/bin/bash` as the first line. 
Tasker might be using `/system/bin/sh` as default.

**Comment by ionlyaskforeden** [comment]
Wow that did the trick!

Thank you.
