### ISSUE TITLE
Any way to output variables?

### ISSUE THREAD

**Issue by fagcinsk** [termux/termux-tasker#17]
Only one way communication here?
stdout/err?

**Comment by ks9208661** [comment]
Here's a [workaround](https://glow.li/technology/2016/4/03/pass-variables-from-termux-to-tasker/).

**Comment by Archenoth** [comment]
So, I referenced all the issues the above pull request solved last year, but I never actually posted in them. Ooops

But yeah! You can now use `%stdout`, `%stderr`, and `%result` in subsequent actions! So, to get data back from Termux in Tasker, you just need to write to the terminal on either standard stream and/or return an exit status that interests you.

![A Tasker configuration screen showing termux ready to run a script with a description of the three above variables it will output](https://user-images.githubusercontent.com/1385527/98742372-94cf0480-236b-11eb-82e0-458e8a5289b1.png)

**Comment by agnostic-apollo** [comment]
This was solved in version [0.4](https://github.com/termux/termux-tasker/pull/26) and should be closed.
