### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by paulsavo1** [termux/termux-tasker#18]
Hi can someone please help me, i had used termux boot to setup a script to run at boot

python sstvProxy.py -hl

hower, it is causing conflicts on my setup as the script is starting before other apps, can someone explain how i could use termux task to start the script a few mins after boot

**Comment by Grimler91** [comment]
Don't open duplicate issues: https://github.com/termux/termux-boot/issues/24

**Comment by paulsavo1** [comment]
i didnt know what forum to post in

**Comment by Grimler91** [comment]
Spamming is seldom the right solution

**Comment by paulsavo1** [comment]
maybe you could actually help rather than getting on like a school teacher

**Comment by paulsavo1** [comment]
ok so so no help then?

**Comment by xeffyr** [comment]
> how i could use termux task to start the script a few mins after boot

Is it a trouble with adding delay ? Did you know about command 'sleep' ?

```
#!/data/data/com.termux/files/usr/bin/bash

# wait 5 minutes
sleep $((5 * 60))

# then execute script
python sstvProxy.py -hl
```

***

In [termux-tasker/issues] we discuss **only** bugs and feature requests related to Termux:Tasker. Questions about how to implement something in shell script should go to Gitter or Google+ pages.
