### ISSUE TITLE
Termux Task not working

### ISSUE THREAD

**Issue by ElectroXexual** [termux/termux-tasker#2]
Termux:Task isn't working for me for some reason...the task gets executed but script never runs
the script is in "~/.termux/tasker" folder, I have tried with both "Execute in a terminal session" checked and unchecked and simply nothing happens, it doesn't even show a blank terminal window
Tasker Run log here http://paste.ubuntu.com/23863288/
I have installed Termux and all it's plugin's from f-droid
Termux version : 0.46
Termux:Task version : 0.1
Android version : 5.1.1 lollipop
Device : VivoV3Max
ty

**Comment by fornwall** [comment]
Does running `logcat` output anything interesting?

**Comment by ElectroXexual** [comment]
Didn't try that, do I have to run "logcat" and run tasker task?

**Comment by ElectroXexual** [comment]
Here's the log from termux when I ran 'logcat' and tested a tasker task http://paste.ubuntu.com/23863520/

**Comment by Fogapod** [comment]
Was the same issue. Creating `file.py` inside of tasker folder solved that
