### ISSUE TITLE
Interpreter/shebang  bug

### ISSUE THREAD

**Issue by allanrps** [termux/termux-tasker#23]
The shebang path to /usr/bin/env works fine when running youtube-dl straight from termux, but when using the tasker plugin it caused the program to fail. When the binary was edited to /bin/env the program ran as expected. It seems that whatever prefixing/redirecting Termux does for the interpreter was not integrated into the Termux: Task plugin.

**Comment by Grimler91** [comment]
`/data/data/com.termux/files/usr/bin/env` would be the proper shebang path. [Termux-exec](https://wiki.termux.com/wiki/Termux-exec) is responsible for automatically fixing shebangs, and it isn't incorporated in any of the addon apps as you noted

**Comment by allanrps** [comment]
Ah, I did not realise termux-exec was automatically called, I thought I had to explicitly call it. Perhaps it should be integrated into the add-ons as well, given that the user isn't made explicitly aware of this mismatch in any way.

**Comment by xeffyr** [comment]
@allanrps termux-exec is an LD_PRELOAD hook for executables. It cannot be used for Android applications.

**Comment by forresthopkinsa** [comment]
So there's no way to make `termux-exec` work with this tasker plugin?
