### ISSUE TITLE
Any way to get the stdout / stderr of python scripts?

### ISSUE THREAD

**Issue by shadowrylander** [termux/termux-tasker#30]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; Basically what the title says. I can't seem to get python scripts to output anything to the standard output or error, even when using `sys.stdout.write()` + `sys.stdout.flush()`; there seem to be constant permission errors to the scripts. I also ran `termux-setup-storage`, but no luck. <br>
&nbsp;&nbsp;&nbsp;&nbsp; Any help would be greatly appreciated!

**Comment by anysou** [comment]
你试下：
os.system('echo "test"')

**Comment by shadowrylander** [comment]
Actually, I realized the reason was that, apparently, you can't run any scripts from the sdcard due to permission restrictions, which is where my scripts directory was linked to. Thanks for the information either way, though!
