### ISSUE TITLE
After rebooting the phone, Termux: Tasker settings are returned to Battery saver.

### ISSUE THREAD

**Issue by lavaed** [termux/termux-tasker#35]
The add-on does not work in the background. constantly have to restore the "Background settings" in "No restrictions". After reboot, "Background settings" automatically switches to "Battery saver"

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: 0.4
* Android OS version: 7.0 MIUI Global 10.2
* Device model:Redmi Note 4

**Comment by xeffyr** [comment]
Neither Termux nor its add-ons manage battery saving optimization on its own, so Termux:Tasker can't reset its battery setting.

**Comment by lavaed** [comment]
> Neither 
 In MIUI, the battery saver settings for each application are configured individually.
