### ISSUE TITLE
Tasker says plugin error

### ISSUE THREAD

**Issue by damionx7** [termux/termux-tasker#37]
**Problem description**
When i try to select termux tasker plugin from tasker it says plugin error ![Screenshot_20201212-071916818.jpg](https://user-images.githubusercontent.com/6530843/101969470-7bf78e80-3c4a-11eb-8289-4a9a1e36186d.jpg)

**Steps to reproduce**
Just select termux tasker plugin from tasker.
![Screenshot_20201212-071909596.jpg](https://user-images.githubusercontent.com/6530843/101969516-b5c89500-3c4a-11eb-8d11-a53391d3c7a0.jpg)
**Expected behavior**
It should work as it was before updating.

**Additional information**

* Termux application version: 0.103
* Android OS version: 10
* Device model: One plus 7 pro

**Comment by xeffyr** [comment]
Latest version as a lot of changes and more steps for configuration are needed.

Follow https://github.com/termux/termux-tasker#setup-instructions, however I'm suggesting to read the whole readme.

**Comment by damionx7** [comment]
Got it. Thanks.
