### ISSUE TITLE
Termux:Tasker MacroDroid

### ISSUE THREAD

**Issue by Zarc250** [termux/termux-tasker#40]
**Problem description**
MacroDroid
termux: tasker 0.4, 0.5 does not work.  only the previous version is recognized

**Additional information**

* Termux application version: 0.106
* Android OS version: 10
* Device model: SM-J400F

**Comment by agnostic-apollo** [comment]
Firstly, explain "does not work" and "previous version is recognized".

Secondly, even the currently latest version of MacroDroid version `5.8.15` has not requested the permission [`com.termux.permission.RUN_COMMAND`](https://github.com/termux/termux-tasker#comtermuxpermissionrun_command-permission-mandatory) in its `AndroidManifest.xml` which is mandatory for Termux:Tasker version `>= 0.5` to work, so those version won't work. Report that to MacroDroid developer. However, Termux:Tasker version `0.4` should work.

**Comment by yqs112358** [comment]
You can use `adb shell pm grant com.arlosoft.macrodroid com.termux.permission.RUN_COMMAND` to manually grant this permission for Macrodroid.
