### ISSUE TITLE
Get error when trying to use it in Tasker

### ISSUE THREAD

**Issue by GitUpGitUp** [termux/termux-tasker#41]
When I try to select the plugin in Tasker I get the following error:
Error: plugin error: missing, disabled, not exported or no permission receiver, or too many receivers.

**Comment by agnostic-apollo** [comment]
You need to grant tasker [`com.termux.permission.RUN_COMMAND`](https://github.com/termux/termux-tasker#comtermuxpermissionrun_command-permission-mandatory) permission for Termux:Tasker version `>=0.5`.

**Comment by agnostic-apollo** [comment]
@joaomgcd consider showing a better error if tasker is not granted a permission required by the plugin when adding a new action. Currently, executing the `Termux:Tasker` action throws the `receiver com.termux.tasker.FireReceiver requires permission com.termux.permission.RUN_COMMAND which we don't have` `%errmsg`, which is also not too clear from a user perspective. Maybe just request the permission if its missing or just improve both errors?

The `TermuxCommand()` function in `Tasker Function` action has similar issues but its exception is thrown by android and is bit more clear, and is for advance users, so its fine.

Thanks

**Comment by joaomgcd** [comment]
I can't request the permission because it would need to be in the manifest and I can't add all possible plugin permissions to the manifest...
How would you suggest I'd improve the error message?

**Comment by GitUpGitUp** [comment]
Maybe say exactly what you need to grant? I also can't figure out the scripts thing but I was hoping to be able to use variables to run in Termux but it looks like I can't do that. Thanks for your response.

**Comment by agnostic-apollo** [comment]
@joaomgcd 
>I can't request the permission because it would need to be in the manifest and I can't add all possible plugin permissions to the manifest...

Yeah, I am aware of that "security" risk, but we haven't implemented a better system yet for that. You can also only request it if you have declared it in the manifest, like with the code [here](https://stackoverflow.com/a/40394186/14686958) probably. Especially, if you plan to declare AutoApps permissions at least.

> How would you suggest I'd improve the error message?

You can throw the same message for other cases, however, if permission is missing, then simply tell the user `Tasker needs to be granted <permission> from its App Settings for the plugin action to be added or executed. You can find it under Additional Permissions with the label: <label>`. The `label`  or description can be received by [`PermissionInfo PackageManager.getPermissionInfo()`](https://developer.android.com/reference/android/content/pm/PackageManager#getPermissionInfo(java.lang.String,%20int)) and then [`PermissionInfo.loadDescription()`](https://developer.android.com/reference/android/content/pm/PermissionInfo#loadDescription(android.content.pm.PackageManager)). Do `null` checks for both `PermissionInfo` and description objects obviously ;)

From a user's perspective, he has no idea what an activity, receiver, `FireReceiver`, etc is.

**Comment by agnostic-apollo** [comment]
@GitUpGitUp 

> I also can't figure out the scripts thing but I was hoping to be able to use variables to run in Termux but it looks like I can't do that.

What script thing? You can pass variable values as arguments to your scripts. Check the [templates](https://github.com/termux/termux-tasker#templates) for scripts and tasks.

**Comment by khurshid-alam** [comment]
@agnostic-apollo @joaomgcd 

How to grant RUN_COMMAND permission in Android 5.0? Any idea? 

My phone is rooted and I am using termux and termux-tasker from github run action ( with https://github.com/termux/termux-app/pull/2740)

**Comment by agnostic-apollo** [comment]
It should be automatically granted since android 5 didn't have runtime permissions.

**Comment by khurshid-alam** [comment]
@agnostic-apollo That's what I thought. But I can't select the plugin on tasker. It gives the same error ?

![Screenshot_2023-08-10-18-55-42](https://github.com/termux/termux-tasker/assets/1333217/7e5e53d9-8da5-4513-b243-2cc9c41351c0)

termux-tasker_v0.6.0+892bb45-github-debug.apk

**Comment by agnostic-apollo** [comment]
Which version of tasker are you using? It needs to be `> = 5.9.3`. I tested plugin configuration for android 5 on avd and it worked, did not test execution.

https://github.com/termux/termux-tasker/issues/69#issuecomment-1224959444

**Comment by khurshid-alam** [comment]
@khurshid-alam This is odd. I have tasker = 5.14.6. I haven't update it to the latest version.

**Comment by khurshid-alam** [comment]
@agnostic-apollo Thanks. I made it work by updating Tasker app. It is working now.

**Comment by agnostic-apollo** [comment]
Great. Welcome. Maybe it was required for tasker to be installed or updated after the termux app was installed that published the permission. Could have checked permission `granted` status with `dumpsys package net.dinglisch.android.taskerm | grep RUN_COMMAND`

**Comment by khurshid-alam** [comment]
Thanks. I think the issue was restored /userdata partition from backup. Which was missing few bytes may be. That explains why Macrodroid also misbehaving. Updating the app fixed the issue.

**Comment by Bagunda** [comment]
Can someone explain in human terms?
How to add `com.termux.permission.RUN_COMMAND` permission?
Tasker v6.1.32.
Termux v0.118.0.
Termux:Tasker v0.6.0.
Android Lineage 10.
Same problem as described in this topic

**Comment by prurigro** [comment]
pm grant com.termux.tasker com.termux.permission.RUN_COMMAND

**Comment by matejdro** [comment]
@Bagunda 

1. Go to Android's Settings
2. Apps
3. Find Tasker
4. Select Permissions
5. Select Additional Permissions
6. Select Termux
7. Grant

**Comment by ikhwanperwira** [comment]
> @Bagunda 
> 
> 1. Go to Android's Settings
> 2. Apps
> 3. Find Tasker
> 4. Select Permissions
> 5. Select Additional Permissions
> 6. Select Termux
> 7. Grant


In case you didn't found **Additional Permissions** in android settings or your stock android didn't provide additional permissions UI/button like mine (realme 5/android 10).
You can do this:
1. Open tasker
2. Create temporary task
3. Create action, choose **Ask Permission** action.
4. Paste **Required Permissions** to `com.termux.permission.RUN_COMMAND`
5. Fill prompt "Do you want allow this thing?"
6. Save action and Run the action.
