### ISSUE TITLE
Yeecli non functional from tasker

### ISSUE THREAD

**Issue by unresolvedsymbol** [termux/termux-tasker#42]
**Problem description**
I have Python installed and installed a program that allows me to control my lights but the command does not function when called from tasker. I have every permission allowed for termux, tasker, termux:tasker, etc and everything set correctly in `termux.properties` as well as ran `termux-reload-settings` afterwards.
**Steps to reproduce**
```bash
pkg i python
pip install yeecli
echo "allow-external-apps=true" >> ~/.termux/termux.properties
termux-reload-settings
```
See: 
![Screenshot_20210331-155005_Termux_Tasker](https://user-images.githubusercontent.com/48220091/113210055-20580d80-9207-11eb-95cd-476ba079b6c1.png)

**Expected behavior**
The command should run etc my light should toggle.

**Additional information**

* Termux application version: 0.108
* Android OS version: 11 (crDroid)
* Device model: OnePlus 7 Pro

**Comment by unresolvedsymbol** [comment]
The command works perfectly fine from termux as it should

**Comment by unresolvedsymbol** [comment]
![Screenshot_20210331-171324_Permission_controller](https://user-images.githubusercontent.com/48220091/113218049-71bcd700-92b1-11eb-9100-fdba6764941c.png)

**Comment by unresolvedsymbol** [comment]
I will try your timeout suggestion but I'm pretty sure I tried tweaking that around

**Comment by unresolvedsymbol** [comment]
![Screenshot_20210331-171530_Tasker](https://user-images.githubusercontent.com/48220091/113218189-adf03780-92b1-11eb-9612-78de808e77cb.png)
No dice

**Comment by agnostic-apollo** [comment]
Disable the `Execute in terminal session` toggle, set timeout to `10s` and flash `%stdout` and `%stderr` with a `Flash` action. Does the action even run successfully, green or red dot?

If that doesn't tell you anything, then we can check the logcat.

**Comment by unresolvedsymbol** [comment]
Yes the task stays green, I've tried both with and without "exec in terminal session" unfortunately I'm not too familiar with variables in tasker so I couldn't seem to get it to flash the stdout but here's an extract from logcat along with some device info: https://a.pomf.cat/ogfott.zip

**Comment by xeffyr** [comment]
It may not work under tasker if `yeecli` shebang is standard (like `#!/usr/bin/env python` or similar). All its parts should be fixed with utility `termux-fix-shebang`.

Reason why it works under Termux session is that `termux-exec` (https://wiki.termux.com/wiki/Termux-exec) is being used for interactive shell.

**Comment by agnostic-apollo** [comment]
Yeah, that might actually be it and that would show as `bad interpreter` errors with a successful action.

It's also mentioned in the README.

https://github.com/termux/termux-tasker#termux-environment

Another reason why stderr should always be checked when running shell commands. There are template tasks available as well that test everything for you, specially if you are not skilled in tasker.

https://github.com/termux/termux-tasker#templates

**Comment by unresolvedsymbol** [comment]
![Screenshot_20210331-203122_Tasker](https://user-images.githubusercontent.com/48220091/113231204-7c5b7a00-9279-11eb-9a05-38da5c04a515.png)
This is what happens unfortunately.
Yes I've added a script to ~/.termux/tasked with
```bash
#!/data/data/com.termux/files/usr/bin/env bash
yee --ip 192.168.1.178 toggle
```

**Comment by unresolvedsymbol** [comment]
(Screenshot shows wrong binary but I switched it to the script)

**Comment by agnostic-apollo** [comment]
It wouldn't matter what your initial script shebang is since termux will handle it. However, the shebangs of all scripts like `yee` called **inside** your script matter. But apparently it's not showing an error, was the toggle disabled when you did the flash? Did logs show anything?

**Comment by unresolvedsymbol** [comment]
Check the logcat zip attached earlier, lmk if it has anything useful

**Comment by agnostic-apollo** [comment]
It didn't cause you are supposed to set log level to debug and then run the action like I said. Without it Termux:Tasker won't log parameters and results.

And how did you even grab that logcat?

**Comment by unresolvedsymbol** [comment]
![Screenshot_20210331-220349_Termux_Tasker](https://user-images.githubusercontent.com/48220091/113237773-b4a48d80-9264-11eb-9de0-9266c394fe14.png)
![Screenshot_20210331-220405_Tasker](https://user-images.githubusercontent.com/48220091/113237783-b79f7e00-9264-11eb-87dc-136228247893.png)
I've had these set if this is what you're referring to. Also maltog (modernized catlog)

**Comment by agnostic-apollo** [comment]
I was referring to the first picture, it's fine. But did you create the zip after setting it to verbose or before? If before, then it should have had entries with `termux-tasker` tag. Try capturing again.

**Comment by agnostic-apollo** [comment]
Closing since currently inactive. Can be opened again if more info is provided.
