### ISSUE TITLE
Erro de Instalação

### ISSUE THREAD

**Issue by ViniciusRodegheri** [termux/termux-tasker#43]
![Screenshot_20210411-083233_NetHunter Store](https://user-images.githubusercontent.com/75143011/114302726-a5adae80-9aa0-11eb-8302-0002cab0129b.jpg)

**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version: Termux Task 0.4
* Android OS version: 10
* Device model: Samsung Galaxy A10 - SM-205G/DS

**Comment by xeffyr** [comment]
You shouldn't mix installations from Google Play and F-Droid. Termux app and add-ons like Termux:Tasker should be installed from same source.
