### ISSUE TITLE
Task script with `termux-notification` hangs

### ISSUE THREAD

**Issue by kontsaki** [termux/termux-tasker#44]
Hello, any idea how can i debug this? i've tried pretty much everything i could think of, like with the tasker plugin action option to "execute in a terminal session" or not, setting termux/tasker/termux:tasker/termux:api to be able to run in the background without battery optimization. The process just hangs. Also testing the tasker action through tasker has the same behavior.
Running the script manually through termux works as expected.

**Comment by agnostic-apollo** [comment]
Check  [Debugging](https://github.com/termux/termux-tasker#debugging) section. But issue is directly related to termux/termux-app#1925.

**Comment by kontsaki** [comment]
Thanks for the reply @agnostic-apollo. Sorry, i somehow missed that issue, closing this.

**Comment by agnostic-apollo** [comment]
Welcome.
