### ISSUE TITLE
Where is the latest version?

### ISSUE THREAD

**Issue by redstreet** [termux/termux-tasker#54]
Apologies for the silly question but the documentation refers to version 0.6.0. The latest release I see is 0.5. Am I not looking at the right place? Thank you.

**Comment by agnostic-apollo** [comment]
It has not been released yet. Things had to be added in `termux-app/termux-shared` which were required by `termux-tasker`. Some have been, although not all, will look into making a release soon.

**Comment by redstreet** [comment]
Good to know. Thanks a bunch for writing and sharing termux tasker, btw. It does exactly what I need 🙂.

**Comment by agnostic-apollo** [comment]
Welcome. `v0.6.0` is out.

https://github.com/termux/termux-tasker/releases/tag/v0.6.0
