### ISSUE TITLE
`allow-external-apps` property not recognized if `~/.termux/termux.properties` is a symlink

### ISSUE THREAD

**Issue by laurentlbm** [termux/termux-tasker#56]
**Problem description**

On my system, `~/.termux/termux.properties` is a symlink, and the source file contains `allow-external-apps = true`. 
Termux:Tasker **0.6.0** doesn't seem to see the file or setting. It worked in the previous version, 0.5.

![Screenshot_20220225-184843294 (1)](https://user-images.githubusercontent.com/1180863/155818573-86449f39-7bb6-42e2-baf4-593c5d2e36d8.jpg)
![Screenshot_20220225-184946444 (1)](https://user-images.githubusercontent.com/1180863/155818577-e6582c7c-5c6f-4924-9cb4-beb7ae170149.jpg)

**Steps to reproduce**

Move `~/.termux/termux.properties` elsewhere and create a symlink in its place:
```
mv ~/.termux/termux.properties ~/
ln -s ~/termux.properties ~/.termux/termux.properties
```

Create a Tasker task that calls an executable outside of `~/.termux/tasker`, for example `/data/data/com.termux/files/usr/bin/nano`

It won't work, Tasker will show an error.

**Expected behavior**

The executable should be called.

**Additional information**

* Termux application version: 0.118.0
* Termux:Tasker application version: 0.6.0
* Android OS version: 11
* Device model: OnePlus 8

**Comment by laurentlbm** [comment]
I understand. Thanks for the explanation and for all your work.

**Comment by agnostic-apollo** [comment]
You are very welcome.
