### ISSUE TITLE
configurable stdout size

### ISSUE THREAD

**Issue by roizcorp** [termux/termux-tasker#57]
As a user I use  a lot of commands in which list many many values, and I need to pass them on for processing, as Termux Tasker cannot execute multiple commands via pipe char I need to pass the data via %stdout, the problem is it is limited to very small size, I have a list of more than 10k items and only about 3199 is within the %stdout when the variable is available in Tasker. While I understand that keeping the var size is for my own good, I would like a way to configure it so it will serve my purposes perhaps via the termux.properties file?

**Comment by agnostic-apollo** [comment]
> lot of commands in which list many many values, and I need to pass them on for processing, as Termux Tasker cannot execute multiple commands via pipe char I need to pass the data via %stdout

You are not making any sense, `%stdout` is a return variable.

If you are passing the variable value returned to a second action, you can just create a single script to process data.

And total data returned from termux:tasker is `100KB` to prevent android throwing `TransactionTooLargeException`. It cannot be changed, you should use physical script files.

https://github.com/termux/termux-tasker#plugin-variables

https://github.com/termux/termux-app/commit/a2209ddd

And there is also limit on data you can pass as arguments.

https://github.com/termux/termux-tasker#arguments-and-result-data-limits
