### ISSUE TITLE
Does this open up an Intent API so other applications can send Termux commands?

### ISSUE THREAD

**Issue by rjsteinert** [termux/termux-tasker#6]
We have an app we would like to be able to send commands to termux. Is there an Intent API for this?

**Comment by yut23** [comment]
It looks like this is built into the main Termux app. See https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/TermuxService.java#L124.

It's used in https://github.com/termux/termux-tasker/blob/master/app/src/main/java/com/termux/tasker/FireReceiver.java.

**Comment by fornwall** [comment]
@rjsteinert Are you still interested in this? As @yut23 says the functionality is there but is not yet exposed, perhaps it could be done by requesting a custom permission?

**Comment by rjsteinert** [comment]
@fornwall For the time being we've managed to package up node and dat into an APK thanks to our ability to compile it in Termux and then get it going as a shared library. For the future, I bet I'll run into a case where it would be handy :-)

**Comment by zcattacz** [comment]
I am using easer https://github.com/renyuneyun/Easer which seems a quite active automation tool . It support dispatching customized intent as action. Is it possible to trigger termux scripts from Easer?

**Comment by fagcinsk** [comment]
Use Automagic, Luke

**Comment by MisterY** [comment]
It's a good start. Requires manually adding scripts to ~/.termux/tasker/ and running them through an app that can run Tasker plugins.
It would be even more convenient to invoke the Termux intent directly and hopefully that is also coming at some point. That would eliminate two components from the process - the addon and a third-party app.

**Comment by xeffyr** [comment]
If need the Intent API for executing commands in Termux, check out https://github.com/termux/termux-app/blob/master/app/src/main/java/com/termux/app/RunCommandService.java#L24-L61.
