### ISSUE TITLE
incorrect representation of commands in README

### ISSUE THREAD

**Issue by dilipkn007** [termux/termux-tasker#61]
Mistake in representing commands [here](https://github.com/termux/termux-tasker#allow-external-apps-property-optional) in readme file leads to confusion 

![Screenshot_20220302-085750~2.png](https://user-images.githubusercontent.com/64477187/156291148-f978062c-70c0-478d-97ab-b9341e4a9819.png)

**Comment by agnostic-apollo** [comment]
Thanks. I have fixed it.
