### ISSUE TITLE
termux-services cant be called via termux-tasker

### ISSUE THREAD

**Issue by north3221** [termux/termux-tasker#62]
**Problem description**
When I use termux services to start or stop a service i.e. sv up httpd it works fine in termux but in termux-tasker it errors 'unable to change to service directory'

I call this via a simple one line script in /termux/taskser. Works in termux directly

I am sure it must be something I am doing, maybe working directory? but I cant figure it out, could be permissions?

I've tried running in tasker directly with tasker function, having set termux properties to allow external. Same issue

**Steps to reproduce**

**Expected behavior**
Calling termux-services should work from tasker the same as directly in termux

**Additional information**

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: s22 ultra

**Comment by agnostic-apollo** [comment]
Could be https://github.com/termux/termux-tasker#termux-environment. Run with `tudo`.

**Comment by north3221** [comment]
> Could be https://github.com/termux/termux-tasker#termux-environment. Run with `tudo`.

It certainly looks like its along the right lines... but do doesn't fix it... So I have full path shebang and even run termux-fix-shebang on the file... I have now installed tudo in bin dir, and chmod 700, added tudo sv up httpd to my script

again still works in termux directly, not in tasker plugin. Still cant change to service directory, thinks it doesn't exist. 

Must be something in sv trying to use a standard path instead of the termux data dir, but wouldn't tudo of taken care of that?

**Comment by Grimler91** [comment]
Please share the script you are trying to run

**Comment by north3221** [comment]
It's literally just the one liner

```
#!/data/data/com.termux/files/usr/bin/bash
tudo sv $1 httpd
```

**Comment by north3221** [comment]
I appreciate this is very likely user error btw 🤣

**Comment by north3221** [comment]
anyone any thoughts on this?

**Comment by agnostic-apollo** [comment]
Set `$PREFIX/bin/tudo` as executable and `-s "source $PREFIX/etc/profile.d/start-services.sh; sv-enable httpd"` as argument.

The `start-services.sh` runs `export SVDIR=$PREFIX/var/service` which is required by `sv`. It's normally sourced when shell starts, but wouldn't be sourced for plugin, hence the issue.

https://github.com/void-linux/runit/blob/82d46804143bc0de7bb9acd728cb951a78112af4/src/sv.c#L368

https://github.com/termux/termux-services

**Comment by north3221** [comment]
Legend. That works! Thanks 👍

**Comment by agnostic-apollo** [comment]
Welcome.
