### ISSUE TITLE
Stdin still expects a file/path

### ISSUE THREAD

**Issue by DoganM95** [termux/termux-tasker#65]
**Problem description**
I am trying to run a shell-command only using stdin, without creating a shell script file. The docs say "use stdin", but after entering my command into stdin, it still expects an executable (file path).
When going back (and ignoring the message), it says "Error: no plugin configuration data.".

**Steps to reproduce**
1. Create a task and use termux plugin
1. Enter a command in stdin, e.g. `ping -c 1 google.com`
1. Leave "Executable" field empty
1. Click done and go back

**Expected behavior**
Should not expect an executable file, when std in is used.
Ideally, the user should be able to choose, wether to use an executable or stdin.

**Additional information**

* Termux application version: 0.118.0
* Android OS version: 12
* Device model: Pixel 3 XL

**Comment by DoganM95** [comment]
For now i created a shell script in ~/.termux/tasker Which forks fine as a temporary solution in my case

**Comment by agnostic-apollo** [comment]
Read the docs again at https://github.com/termux/termux-tasker#stdin

Standard input needs to be passed to some process/executable which executes it, you can't pass it to nothing. For bash shell scripts, set executable to `$PREFIX/bin/bash`
