### ISSUE TITLE
Error installing Termux Tasker 

### ISSUE THREAD

**Issue by mora145** [termux/termux-tasker#73]
Hi.
I'm trying install Termux Tasker, first I install Termux via PlayStore, and after try install Tasker plugin obtaining the error:

![Screenshot_20221020-101425337](https://user-images.githubusercontent.com/25883820/196971510-487dc7c7-728f-44ab-bcb4-738dd5efd2e2.png)

**Comment by agnostic-apollo** [comment]
>Check [termux-app Installation](https://github.com/termux/termux-app#Installation) for details before reading forward.

https://github.com/termux/termux-tasker#installation
