### ISSUE TITLE
stdout not working with Tasker

### ISSUE THREAD

**Issue by CanYouJustWorkPlease** [termux/termux-tasker#80]
**Problem description**

I've followed this [guide](https://old.reddit.com/r/tasker/comments/ly5y6j/guide_using_termuxtasker_plugin_to_execute/) to make Termux:Tasker run in Tasker, but, unfortunately, when I got to the part of printing the output stored in the variable %stdout, by using Tasker's Flash action, I only got displayed "%stdout", instead of getting displayed:

hello 
hello world

![t1](https://user-images.githubusercontent.com/73692469/205493563-3c0a449a-0f06-49f5-be90-f1ae64df9204.jpg)

On the other hand I had success with Macrodroid, where Microdroid's "Popup message" action displays:

hello 
hello world

, once the floating button is pressed.

![t2](https://user-images.githubusercontent.com/73692469/205493596-9772d97b-7b1b-4700-8414-4b0cced6b531.jpg)

For Macrodroid I assigned the global variable "notify" as the output variable of Termux:Tasker, respectively acting the same as %stdout is acting for Tasker.

![t3](https://user-images.githubusercontent.com/73692469/205493601-252ed31e-8fd7-43f1-8387-b59bc98e630e.jpg)

**Steps to reproduce**

Follow the same steps as in this [guide](https://old.reddit.com/r/tasker/comments/ly5y6j/guide_using_termuxtasker_plugin_to_execute/) .

**Expected behavior**

Tasker doesn't display:

hello 
hello world

upon using %stdout variable, the output variable of Termux:Tasker, by using Tasker's Flash action.

**Additional information**

* Termux application version: 0.118.0 (F-Droid)
* Termux:Tasker application version: 0.6.0 (F-Droid)
* Android OS version: 10
* Device model: Huawei P40 lite E
* Tasker version: 6.0.10
* Macrodroid version: 5.27.8

**Comment by agnostic-apollo** [comment]
Check what other variables are set to.

https://github.com/termux/termux-tasker#plugin-variables

**Comment by CanYouJustWorkPlease** [comment]
Thank you for helping out! Unfortunately that didn't work, even if I set the timeout to 10, 60 or even 3600. None of the variables would output anything.

I'll resort to Macrodroid instead.

**Comment by CanYouJustWorkPlease** [comment]
Yes, I have granted it through 2 methods, one from permissions, and one by running [this](https://old.reddit.com/r/tasker/comments/ly5y6j/guide_using_termuxtasker_plugin_to_execute/it1mb8i/). I also have granted whatever permissions Tasker asked for, all from Applications > Permissions.

I have also granted it "write system settings", "draw over other apps", "usage", "do not disturb" and "administrator" access. I have also performed all the settings described in dontkillmyapp.com for Huawei.

This is the the entire debug output (I selected "Debug" for "Log level" in Termux:Tasker; I didn't find how to set "Debug" "Log level" for Termux, as I can't see any 3 dots in it) once I ran the task involving Termux:Tasker and Flash:
![t4](https://user-images.githubusercontent.com/73692469/205513952-422fc457-f7ac-4c14-83de-b06ffb7c485b.jpg)

**Comment by agnostic-apollo** [comment]
Even with default log level, there should be an entry for `Received execution intent` logged by termux-tasker, and since there isn't, it means it didn't even receive the execution intent to process it. So your OS must not delivered it, you may need to enabled `Auto Start` in your android settings for termux-tasker. Basically, not a termux-tasker issue. You can check full system `logcat` logs with `adb`/`su` from pc/termux and you may find the exact reason, look for entries for `com.termux.tasker`.

https://github.com/termux/termux-tasker/blob/51451acaba236f0ec419e5601e928f489a6a9974/app/src/main/java/com/termux/tasker/FireReceiver.java#L53

>I didn't find how to set Debug Log level for Termux

Termux terminal has a left drawer, swipe towards right from left side of screen and click settings icon.

**Comment by CanYouJustWorkPlease** [comment]
Thank you for the help and for all the advices!

I finally managed to make it work by uninstalling Tasker and all of its all plugins, restarting the phone, and installing them back again. Prior to this I've previously only reinstalled Tasker.

**Comment by agnostic-apollo** [comment]
You are welcome.

I assume next step would have been to factory reset? ;)

**Comment by CanYouJustWorkPlease** [comment]
I'm not a daredevil like that, but I would've tried Macrodroid instead :P

Thanks for making Termux and all of its plugins!

**Comment by agnostic-apollo** [comment]
Ah, so a deserter, such a shame!

I am not the creator of termux apps and plugins, just the current maintainer, but welcome.
