### ISSUE TITLE
httpie binary doesn't work in background

### ISSUE THREAD

**Issue by anaschaudhary33** [termux/termux-tasker#83]
**Problem description**
http request through httpie works only when executed in terminal session and terminal session action set to 0 or 1 but not otherwise.

**Steps to reproduce**
Setup a new task to run http binary
1.Uncheck execute in terminal session 
Or 
2. Check execute in terminal session and set terminal session action to 2 or 3

**Expected behavior**
httpie work in background also just like when running in terminal session.

**Additional information**

* Termux application version:Version 0.118.0+2f5a6f7
* Android OS version: 11
* Device model: OnePlus 7

**Comment by agnostic-apollo** [comment]
Define "doesn't work".

Also have you checked https://github.com/termux/termux-tasker#termux-environment

**Comment by anaschaudhary33** [comment]
I am getting the following error 
 @![Screenshot_20230126-235904__01](https://user-images.githubusercontent.com/70742968/214920983-6d54a112-46f0-4879-8124-31903ac7c558.jpg)

**Comment by agnostic-apollo** [comment]
That seems to be a timeout error because the task didn't complete in 10s. You can check for such errors with `%err` and `%errmsg` variables. Use template tasks if you don't know how.

https://github.com/termux/termux-tasker#Plugin-Variables

https://github.com/termux/termux-tasker#templates

**Comment by anaschaudhary33** [comment]
% errmsg is `timeout`
% err is `2`.

However this task takes only 2 seconds when 'executed in a terminal session' is checked. 

And if I set timeout to none, than task never complete (when executed in terminal session is uncheck or terminal session action set to 2 or 3).

**Comment by agnostic-apollo** [comment]
Your script commands may not support running in background shell and/ could be hanging. Check logcat logs.

https://github.com/termux/termux-tasker#Debugging

**Comment by anaschaudhary33** [comment]
[logcat.txt](https://github.com/termux/termux-tasker/files/10528967/logcat.txt)

**Comment by agnostic-apollo** [comment]
>TermuxCommand: [29863-stderr] > warning: no stdin data read in 10.0s (perhaps you want to --ignore-stdin)
>TermuxCommand: [29863-stderr] > See: https://httpie.io/docs/cli/best-practices

**Comment by anaschaudhary33** [comment]
Thank a lot.
It's working now..

**Comment by agnostic-apollo** [comment]
Welcome.
