### ISSUE TITLE
My script output dissappears immediately after running

### ISSUE THREAD

**Issue by richardeakin** [termux/termux-tasker#84]
Hi,

I have a couple scripts (some small git repo syncing things) successfully running, however I'm having trouble seeing what they are doing. I have discovered the "Draw Over Apps permission" step and enabled that, and now I can see the script output, however it disappears too fast for me to read anything. Is there any way to keep that output window on screen, or go back to it (ideally I'd like the option to do both of those things).

Thank you for the help and cool little app / widget.

Android version: 13

**Comment by agnostic-apollo** [comment]
Add `read -n 1` at end to have to keep terminal waiting for a key press.

**Comment by richardeakin** [comment]
Thanks for the tip. It works although I do get an error message from it that I don't understand:

sh: 12: read: Illegal option -n
