### ISSUE TITLE
Script not found 

### ISSUE THREAD

**Issue by PeterKW** [termux/termux-tasker#97]
I've got a bit stuck trying to get tasker to find a python file to run in tasker

Any suggestions of what to try next?

![Screenshot_20230923-163433.png](https://github.com/termux/termux-tasker/assets/13779157/08fd7038-fdc4-4e8a-9027-e9f15d497cca)

![Screenshot_20230923-164524.png](https://github.com/termux/termux-tasker/assets/13779157/095b6f0f-f335-445d-8c30-4726752e85c4)

![Screenshot_20230923-164356.png](https://github.com/termux/termux-tasker/assets/13779157/4fa20d2f-eb26-4c0f-b6c2-93df4da3cf6a)

![Screenshot_20230923-164423.png](https://github.com/termux/termux-tasker/assets/13779157/78b3b980-be14-4b23-9300-dbad25f9c972)

**Comment by PeterKW** [comment]
![Screenshot_20230923-165043~2.png](https://github.com/termux/termux-tasker/assets/13779157/ab657d77-2473-4ccf-91ca-f11be3fb0bb1)

**Comment by PeterKW** [comment]
Done these as well

allow-external-apps property to true.
mkdir -p /data/data/com.termux/files/home/.termux/tasker
chmod 700 -R /data/data/com.termux/files/home/.termux
com.termux.permission.RUN_COMMAND

**Comment by agnostic-apollo** [comment]
Might be related to https://github.com/termux/termux-tasker#termux-environment

Configuration screen would show an error if it was failing to find the file you entered. And you don't need `allow-external-apps` enabled for tasker directory, read the docs.

**Comment by PeterKW** [comment]
> Might be related to https://github.com/termux/termux-tasker#termux-environment
> 
> Configuration screen would show an error if it was failing to find the file you entered. And you don't need `allow-external-apps` enabled for tasker directory, read the docs.

Perhaps I can't call a python script using tasker?

**Comment by agnostic-apollo** [comment]
Of course you can, try fixing shebang or use `tudo`.

There are working `python` script templates available too.

**Comment by PeterKW** [comment]
That might have worked! Thanks

**Comment by PeterKW** [comment]
> Of course you can, try fixing shebang or use `tudo`.
> 
> There are working `python` script templates available too.

What does tudo do?

**Comment by PeterKW** [comment]
The Termux notification says that I have one task running. How do I see what the task is doing currently?

**Comment by agnostic-apollo** [comment]
Welcome

> How do I see what the task is doing currently?

https://github.com/termux/termux-tasker#debugging

https://github.com/termux/termux-tasker#custom-log-level
