### ISSUE TITLE
bash - "Arguments" doesn't accept bash commands

### ISSUE THREAD

**Issue by francwalter** [termux/termux-tasker#98]
Hello

I have termux-tasker 0.6 on Tasker 6.2.15-rc on Android 9.0 (unrooted).  

termux-tasker is working well, when I use a binary with arguments, e.g.:

Exec.: `/data/data/com.termux/files/usr/bin/ls`
Arg.: `-alt`

This gives me the `ls -alt` output of actual path (home in this case).

But now I need to run a for-do-done loop to read all files in a folder. In the normal bash of Termux I can do something like:

`for file in ./*; do echo "${file}"; done;`

And I get an output of the files in the actual dir.
But this does not work in termux-tasker.
I set as "Executable":

` /data/data/com.termux/files/usr/bin/bash`

and as "Arguments" I set:

` for file in ./*; do echo "${file}"; done; `

But I get as stderr:

` /data/data/com.termux/files/usr/bin/bash: for: No such file or directory `

Now I dont know what is not working, if it is just a simple syntax question, or if that feature is just not implemented like that.
I didnt find it in the description of termux-tasker. bash as Executable seems different.

My goal is, to make an encrypt-decrypt Task with gpg in Termux, as there is nothing like this for Tasker (only in the direct Tasker version, which I have, but want to leave for some reasons).

Thanks for any help.
frank

**Comment by agnostic-apollo** [comment]
Pass script in stdin.

**Comment by francwalter** [comment]
So easy the solution, thank a lot, and so fast 👍 
I spend some time with try and error ...
Thanks!!!

**Comment by agnostic-apollo** [comment]
Welcome.
